

spring:
  config:
    activate:
      on-profile: local
    import: "optional:configserver:"
  data:
    redis:
      host: localhost
      port: 6379
  cloud:
#    config:
#      enabled: false

    gateway:
      discovery:
        locator:
          enabled: true
      routes:

        #================================++#

        #member Server
        - id: user-service-test
          uri: lb://MEMBER-SERVER
          predicates:
            - Path=/api/auth/health
server:
  port: 8000
